apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-static-provisioner
  namespace: default
  labels:
    helm.sh/chart: provisioner-2.5.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: local-static-provisioner
